drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists shopping_cart_items cascade;
drop table if exists shopping_carts cascade;
drop table if exists reviews cascade;
drop table if exists users cascade;
drop table if exists products cascade;
drop table if exists categories cascade;


CREATE TABLE IF NOT EXISTS users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(16)        NOT NULL,
    email    VARCHAR(32) UNIQUE NOT NULL,
    password VARCHAR(1024),
    address  VARCHAR(4096),
    role     VARCHAR(16)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    description VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS products
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(32) NOT NULL,
    description VARCHAR(1024),
    price       DECIMAL(10, 2) NOT NULL,
    category_id INT,
    stock       INT,
    imageUrl    VARCHAR(4096),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS orders
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INT         NOT NULL,
    order_date   TIMESTAMP   NOT NULL,
    status       VARCHAR(16) NOT NULL,
    total_amount DECIMAL(10, 2),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS order_items
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   INT NOT NULL,
    product_id INT NOT NULL,
    quantity   INT NOT NULL,
    price      DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders (id),
    FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE IF NOT EXISTS shopping_carts
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS shopping_cart_items
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    INT NOT NULL,
    product_id INT NOT NULL,
    quantity   INT NOT NULL,
    FOREIGN KEY (cart_id) REFERENCES shopping_carts(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS reviews
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    user_id   INT NOT NULL,
    rating    INT,
    text      VARCHAR(1024),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
